### ISSUE TITLE
Displaying shiny components on htmltemplate

### ISSUE THREAD

**Issue by mattkumar** [vivekkatial/uber_shiny#1]
Hi Vivek,

First, very cool app!

I'm also using the Glint html template for a small project. One general issue I'm having with it is related to shiny reactive outputs. For example, I'm trying to create a select input with some choices, and simply have a textOutput on the app list those choices. While I can get the select input and the textOutput to show up (by modifying the index.html), when I select a different option, the textOutput doesn't update.

I saw that your uber_app also used the Glint template and I tried to get my example to work in there and it did. Additionally, using your app, I was also able to do other things I couldn't in my version of the Glint template (e.g. add a datatable output; DTOutput)

My main question is whether there is something I'm overlooking that prevents this kind of activity to occur or how did you get it to occur (e.g. in your app, you can select from a list of cities and leaflet updates). I know there a lot of dependencies in the template, both css and js, admittedly i don't know too much about, but was wondering if you had any general insights.

I've noticed this issue with working with other html templates with assets too.

Thanks!

**Comment by vivekkatial** [comment]
Hey Matt,

Did you try removing the `jquery` dependency on the bottom of the `index.html`. Because when we load the shiny app dependencies it also imports a different `jquery` which will clash with the application.
